class AppDetails {
  static const String version = "v1.0.2";
  static const String developer = "thetwodigiter";
  static const bool isBeta = false;
  static const String repoURL = "https://github.com/iamthetwodigiter/ShinobiHaven";
  static const List<Map<String, dynamic>> changelogs = [
    {
      "v1.0.2": {
        "title": "Accent & Theme Improvements",
        "date": "2025-10-06",
        "notes": [
          "Dynamic accent color applied app-wide",
          "AppTheme refactored to use runtime getters so theme sub-objects (AppBar, ProgressIndicator, BottomNavigationBar) pick up the current accent",
          "ThemeProvider enhanced: added accentColor provider and updated ThemeNotifier.setAccentColor to notify app and persist changes",
          "Replaced nested unbounded ListView builders in profile/theme selector with constrained layout (GridView/Wrap) to fix RenderFlex overflow",
          "Progress indicators and bottom navigation selected item color now react to the selected accent",
          "General provider & rebuild fixes so theme changes propagate reliably across the app"
        ],
      },
      "v1.0.1": {
        "title": "Bug Fixes & Performance Improvements",
        "date": "2025-09-21",
        "notes": [
          "Fixed critical video player persistence issue between different anime",
          "Resolved video playback continuing when switching between anime from same section",
          "Enhanced provider state management to prevent cross-contamination of video sources",
          "Improved video player initialization with better state validation",
          "Enhanced video URL validation and cleanup to prevent cached playback issues",
          "Enhanced widget lifecycle management for better memory usage and stability",
        ],
      },
      "v1.0.0": {
        "title": "Official Release",
        "date": "2025-09-20",
        "notes": [
          "Official stable release of ShinobiHaven",
          "Added professional splash screen for enhanced app startup experience",
          "Streamlined navigation flow - Watch episodes directly from anime details without multiple page transitions",
          "Smart Watch Now button - Automatically resume from last watched episode or start from Episode 1",
          "Optimized user experience with reduced navigation steps for faster episode access",
          "Improved video player with proper disposal and single instance management",
          "Enhanced episode tracking and last watched functionality with real-time updates",
          "Better error handling and loading states throughout the app",
          "Performance optimizations for smoother streaming experience",
          "Fixed video playback continuing after navigation back",
          "Improved local storage management with Hive boxes for better data persistence",
          "UI/UX improvements and better user feedback across all screens",
          "Comprehensive bug fixes and stability improvements",
          "Advanced notification system for app updates with progress tracking",
          "In-app update checker with automatic download and installation support",
          "Smart notification management preventing spam and duplicate notifications",
          "Enhanced update installation with multiple fallback methods for better compatibility",
          "FileProvider integration for secure APK installation across Android versions",
          "Improved notification actions with proper sound and vibration control",
          "Real-time download progress updates in both dialogs and notifications",
          "Background download support with notification-based progress tracking",
          "Automatic cleanup of old notifications when new ones are generated",
          "Enhanced permission handling for storage and install packages",
          "Comprehensive app data backup and restore functionality",
          "Export and Import user data including favorites, collections, and watch history",
          "Progress indicators for backup and restore operations",
          "Enhanced privacy policy with detailed data handling information",
          "Improved changelog display with version sorting and copy functionality",
          "Better error messages and user feedback throughout the application",
          "Advanced statistics tracking for most watched anime",
          "Better file management for downloads and temporary files",
          "Enhanced security with proper file provider configuration",
          "Improved app startup performance and resource management",
        ],
      },
      "v1.0.0-pre-release": {
        "title": "Initial Release",
        "date": "2025-09-19",
        "notes": [
          "Discovery and browse anime with detailed pages including sorting and filtering",
          "Subbed and Dubbed episodes streaming with multiple format support",
          "Local library system with favorites, custom collections, and watch history",
          "Episode-level watch tracking with detailed statistics",
          "Favorites management with intuitive add and remove functionality",
          "Custom collections creation and management with card-based UI",
          "Watch history tracking with episode count and progress",
          "Top 10 most-watched anime statistics and rankings",
          "User onboarding with profile setup and theme selection",
          "Comprehensive privacy policy integrated within the app",
          "Dark mode support with consistent theming throughout",
          "Responsive design optimized for various screen sizes",
          "Local data persistence using Hive for offline functionality",
          "Search functionality with advanced filtering options",
          "Video player integration with multiple streaming sources",
          "User profile customization with avatar selection",
          "Theme preferences with light and dark mode options",
          "Data consent and disclaimer system for user transparency",
        ],
      },
      "unreleased": {
        "title": "Planned Features",
        "notes": [
          "Manga reading support with integrated viewer",
          "Offline download functionality for episodes",
          "Cloud synchronization for cross-device data sharing",
          "Advanced sorting and filtering options for library management",
          "User ratings and reviews system for anime",
          "Personal notes and comments for anime entries",
          "Enhanced recommendation system based on watch history",
          "Social features for sharing favorites and collections",
          "Episode download queue management",
          "Automatic quality selection based on network conditions",
          "Integration with external anime databases",
        ],
      },
    },
  ];
}
